adaptando el proyecto
The-Software-Design-Company/tsdc-vynils-app pull request #70
Opened 2023-11-03 23:40 UTC by mttm774

2023-11-03 23:42 UTC, mvegaruniandes approved these changes
Approved

2023-11-03 23:43 UTC, zearkiatos commented
@mttm774 revisa por fa que esta fallando el ci

2023-11-03 23:43 UTC, zearkiatos requested changes
Revisar @mttm774 esta fallando el pipeline

2023-11-04 02:57 UTC, mvegaruniandes approved these changes
Approved

2023-11-04 03:00 UTC, zearkiatos approved these changes

2023-11-04 03:03 UTC, merged